from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'UserDashboardData',
    'Account',
    'Session',
    'VerificationToken',
    'Question',
    'UserAnswer',
    'UserWrongdoingQuestion',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'accounts': 'Account',
        'sessions': 'Session',
        'userAnswers': 'UserAnswer',
        'wrongdoingQuestions': 'UserWrongdoingQuestion',
        'dashboard': 'UserDashboardData',
    },
    'UserDashboardData': {
        'user': 'User',
    },
    'Account': {
        'user': 'User',
    },
    'Session': {
        'user': 'User',
    },
    'VerificationToken': {
    },
    'Question': {
        'userAnswers': 'UserAnswer',
        'wrongdoingQuestions': 'UserWrongdoingQuestion',
    },
    'UserAnswer': {
        'user': 'User',
        'question': 'Question',
    },
    'UserWrongdoingQuestion': {
        'user': 'User',
        'question': 'Question',
    },
}

# fmt: on